### Numerical Data

yeild = w1 * temp + w2 * rainfall + w3 * humidity

In [3]:
w1,w2,w3 = 0.2,0.3,0.5

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [6]:
kanto_temp = 73
kanto_rain = 67
kanto_humdity = 43

In [8]:
kanto_yield = kanto_temp * w1 + kanto_rain * w2 + kanto_humdity *w3

kanto_yield

56.2

In [9]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield))

The expected yield of apples in Kanto region is 56.2 tons per hectare.


In [15]:
kanto = [73,67,43] 
kanto

[73, 67, 43]

In [14]:
weights = [w1,w2,w3]
weights

[0.2, 0.3, 0.5]

In [27]:
def crop_yeild(region,weights):
    result = 0
    for x,y in zip(region,weights):
        result += x * y
    return result

In [29]:
crop_yeild(kanto,weights)

56.2

### Numpy Arrays

In [36]:
import numpy as np

In [38]:
#Numpy Array
kanto = np.array([73,67,43])

In [39]:
kanto

array([73, 67, 43])

In [43]:
weights = np.array([0.2,0.3,0.5])

In [45]:
weights

array([0.2, 0.3, 0.5])

In [46]:
type(weights)

numpy.ndarray

In [47]:
weights[0]

np.float64(0.2)

In [51]:
kanto[1]

np.int64(67)

### Numpy Operations

In [52]:
np.dot(kanto,weights)

np.float64(56.2)

In [55]:
(kanto * weights).sum()

np.float64(56.2)

`np.dot()` is a NumPy function used to compute the dot product of two arrays. Depending on the input arrays, it can handle both 1-D and 2-D arrays and can also perform matrix multiplication.

### 1-D Arrays (Vectors)

When `np.dot()` is applied to two 1-D arrays, it computes the dot product of the two vectors.

#### Example:

```python
import numpy as np

# Define two 1-D arrays (vectors)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(a, b)
print(dot_product)  # Output: 32
```

### Explanation:

For vectors {a} = [1, 2, 3]\) and \(\mathbf{b} = [4, 5, 6]\):

{a} \cdot \mathbf{b} = (1 \cdot 4) + (2 \cdot 5) + (3 \cdot 6) = 4 + 10 + 18 = 32 \]

### 2-D Arrays (Matrices)

When `np.dot()` is applied to 2-D arrays (matrices), it performs matrix multiplication.

#### Example:

```python
import numpy as np

# Define two 2-D arrays (matrices)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the matrix product
matrix_product = np.dot(A, B)
print(matrix_product)
# Output:
# [[19 22]
#  [43 50]]
```

### Explanation:

For matrices \(A\) and \(B\):

\[ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} \]

The matrix product \(A \cdot B\) is computed as:

\[ A \cdot B = \begin{bmatrix} (1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\ (3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8) \end{bmatrix} = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix} \]

### Higher-Dimensional Arrays

When `np.dot()` is applied to arrays with more than two dimensions, it performs a sum-product over the last axis of the first array and the second-to-last axis of the second array.

#### Example:

```python
import numpy as np

# Define two higher-dimensional arrays
C = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Compute the dot product
dot_product = np.dot(C, D)
print(dot_product)
```

### Summary

- **1-D Arrays**: Computes the dot product of two vectors.
- **2-D Arrays**: Performs matrix multiplication.
- **Higher-Dimensional Arrays**: Performs a sum-product over the last axis of the first array and the second-to-last axis of the second array.

### Common Use Cases

- **Vectors**: Calculating the dot product for projections, similarity measures, etc.
- **Matrices**: Performing linear transformations, solving systems of linear equations, etc.

The `np.dot()` function is versatile and efficient, leveraging NumPy's optimized C code for fast computations.

In [66]:
arr1 = np.array(0)
arr2 = np.array([1,2])
arr3 = np.array([[1,2],[11,22]])

In [67]:
arr1.ndim, arr2.ndim, arr3.ndim

(0, 1, 2)

In [68]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [69]:
np.dot(arr1,arr2)

np.int64(32)

### Multi-dimensional Numpy arrays 

In [70]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [71]:
climate_data.ndim

2